export const actionTypes = {
	//burger builder action types
	ADDIG:'ADDIG',
	REDUCEIG:'REDUCEIG',
	SETIG:'SETIG',
	FETCH_IG_FAILED: 'FETCH_IG_FAILED',
	//order action types
	PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
	PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
	PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
	PURCHASE_INIT:'PURCHASE_INIT',
	//fetch orders
	FETCH_ORDER_START:'FETCH_ORDER_START',
	FETCH_ORDER_SUCCESS:'FETCH_ORDER_SUCCESS',
	FETCH_ORDER_FAIL:'FETCH_ORDER_FAIL',
	//authentication
	AUTH_START: 'AUTH_START',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_FAIL: 'AUTH_FAIL',
	AUTH_LOGOUT: 'AUTH_LOGOUT'
}